### ISSUE TITLE
Question on playlists

### ISSUE THREAD

**Issue by GerritKuilder** [hamishbrown/easy-radio#1]
I might find  out shortly but still asking does this support playlists?

Gerrit Kuilder

**Comment by GerritKuilder** [comment]
Well, that went smooth, had it up and running in 5 minutes and added to my sonos in another 5 minutes,
A few questions:
The location of the log files: I would like to keep an eye on the logs so a volume for the logs would be helpful, a search for the location of the icecast logs did not help.
Setting the default encoding: I would like to set it higher, it seems to be 128Kbps by default. As I use it for local streaming I can afford to set it to a higher bitrate, again a search did not help me.

(ad I dare not to ask about setting a logo, have to do with some clever naming)

**Comment by GerritKuilder** [comment]
OK, just one more (and I think it will add to the usability of this docker)
I checked the live.liq and found something:
I think a few more examples as this will help me a lot:```mount = "radio", normalize(mksafe(playlist("/tracks"))))```

So the 'mount=' sets the name of the radiostation
normalize I suspect sets the encoding, can this be set to a higher encoding rate?
playlist:/tracks, sets it as that it should play tracks, if you want to play playlists: something like playlist(mode="normal", "/my/pl.m3u")

So if I want to add a radio station with random selected tracks of my Bluegrass and Country selection, that gets generated on a daily basis:

```mount = "BluegrassCountry", normalize(mksafe(playlist("bluegrasscontry.m3u",reload_mode="watch"))))```

Remaining questions:
Can a logo/image be sent?
Can the bitrate be set, as it defaults to 128K?
Can the logs be exported as a volume?

I could write/explain the details a little better after the answers and I am willing to share it for documentation purposes.

**Comment by hamishbrown** [comment]
> I might find out shortly but still asking does this support playlists?
> 
> Gerrit Kuilder

Yes. Map the tracks volume in the container to your local playlist file, eg "/path/to/playlist.pls:/tracks:ro". See https://www.liquidsoap.info/doc-1.4.1/playlist_parsers.html

**Comment by hamishbrown** [comment]
> A few questions:
> The location of the log files: I would like to keep an eye on the logs so a volume for the logs would be helpful, a search for the location of the icecast logs did not help.
> Setting the default encoding: I would like to set it higher, it seems to be 128Kbps by default. As I use it for local streaming I can afford to set it to a higher bitrate, again a search did not help me.
>

In the container at '/var/log/icecast2', map volume to a local log for easy access: 
```
"./icecast_logs:/var/log/icecast2:rw"
```
 
Encoding can be set in live.liq:
```
output.icecast(%mp3(bitrate=256),
    host = "localhost", port = 8000, password = getenv("ICECAST_PASS"),
    mount = "radio", normalize(mksafe(playlist("/tracks"))))
```

**Comment by hamishbrown** [comment]
For more options regarding Icecast and Liquidsoap see relevant documentation

Icecast https://icecast.org/docs/icecast-2.4.1/config-file.html

Liquidsoap https://www.liquidsoap.info/doc-1.4.1/cookbook.html
